spring.application.name=Healthy
spring.datasource.url=jdbc:postgresql://localhost:5432/application_healthy
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true